### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by theavijitsarkar** [saurabhgupta050890/Media-Refresher-Cordova#2]
I downloaded a MP4 using the file transfer plugin.
It went to success block, but no change in gallery

```
path ="file:///storage/emulated/0/Android/data/com.avifa.gifstar/files/c7eec950-0fd3-11e6-b695-7565d05cd59c.mp4"

         var onSuccess = function(result) {
              //Gets the server response object in the form of a string.
              console.log('saved')
          }

          var onFailure = function(errorMsg) {
              console.log("Media Refresh failed:" + errorMsg);
          }

          mediaRefresh.scanMedia(path,onSuccess,onFailure);
```

It works if the file is in the gallery folder. I have no idea on how to transfer the downloaded file to the gallery folder. In cordova how do i find the gallery folder path? Maybe I can directly download there

**Comment by saurabhgupta050890** [comment]
You can give the download target path to gallery path

**Comment by nurfgun** [comment]
image files seem to show up in the gallery fine, but mp4 files don't. success callback is called but nothing shows up in the gallery when its video. Any idea?

**Comment by anujmpec** [comment]
How can i give path to gallery path ?

**Comment by saurabhgupta050890** [comment]
// !! Assumes variable fileURL contains a valid URL to a path on the device,
//    for example, cdvfile://localhost/persistent/path/to/downloads/

var fileTransfer = new FileTransfer();
var uri = encodeURI("http://some.server.com/download.php");

fileTransfer.download(
    uri,
    fileURL,
    function(entry) {
        console.log("download complete: " + entry.toURL());
    },
    function(error) {
        console.log("download error source " + error.source);
        console.log("download error target " + error.target);
        console.log("download error code" + error.code);
    },
    false,
    {
        headers: {
            "Authorization": "Basic dGVzdHVzZXJuYW1lOnRlc3RwYXNzd29yZA=="
        }
    }
);


Here in fileUrl , you can give path to gallery
